var application = angular.module('myApp', []);

application.controller('partnerBanks', ['$scope', function($scope)
	{
        $scope.topBanks = [
            {
                name: "Banco de Oro",   
                acronym: "BDO",
                image: "images/bdo.png",
                "height": "40",
                "width": "140",
                "transform": "translateY(20px)",
            },
            {
                name: "Metropolitan Bank and Trust Company",
                acronym: "MetroBank",
                image: "images/metrobank.png",
                "height": "70",
                "width": "150",
            },
            {
                name: "LANDBANK",
                acronym: "LB",
                image: "images/landbank.png",
                "height": "65",
                "width": "125",
            },
            {
                name: "Bank of the Philippine Islands",
                acronym: "BPI",
                image: "images/bpi.png",
                "height": "60",
                "width": "120",
            }, 
            {
                name: "Philippine National Bank",
                acronym: "PNB",
                image: "images/pnb.png",
                "height": "50",
                "width": "150",
            },
            {
                name: "CHINABANK",
                image: "images/chinabank.jpg",
                "height": "65",
                "width": "125",
            },
            {
                name: "Security Bank",
                acronym: "SB",
                image: "images/secbank.jpg",
                "height": "65",
                "width": "150",
            },
            {
                name: "Rizal Commercial Banking Corporation",
                acronym: "RCBC",
                image: "images/rcbc.jpg",
                "height": "70",
                "width": "135",
            },
        ],

		$scope.allBanks = [
            {
                name: "Banco de Oro",   
                acronym: "BDO",
                image: "images/bdo.png",
                "height": "40",
                "width": "140",
                "transform": "translateY(20px)",
            },
            {
                name: "Metropolitan Bank and Trust Company",
                acronym: "MetroBank",
                image: "images/metrobank.png",
                "height": "70",
                "width": "150",
            },
            {
                name: "LANDBANK",
                acronym: "LB",
                image: "images/landbank.png",
                "height": "65",
                "width": "125",
            },
            {
                name: "Bank of the Philippine Islands",
                acronym: "BPI",
                image: "images/bpi.png",
                "height": "60",
                "width": "120",
            }, 
            {
                name: "Philippine National Bank",
                acronym: "PNB",
                image: "images/pnb.png",
                "height": "50",
                "width": "150",
            },
            {
                name: "CHINABANK",
                image: "images/chinabank.jpg",
                "height": "65",
                "width": "125",
            },
            {
                name: "Security Bank",
                acronym: "SB",
                image: "images/secbank.jpg",
                "height": "65",
                "width": "150",
            },
            {
                name: "Rizal Commercial Banking Corporation",
                acronym: "RCBC",
                image: "images/rcbc.jpg",
                "height": "70",
                "width": "135",
            },
            {
                name: "UnionBank",
                image: "images/unibank.png",
                "height": "65",
                "width": "150",
            },
            {
                name: "EastWest Bank",
                acronym: "EastWest",
                image: "images/eastwest.jpg",
                "height": "50",
                "width": "150",
            },
            
            {
                name: "United Coconut Planters Bank",
                acronym: "UCPB",
                image: "images/ucpb.png",
                "height": "75",
                "width": "135",
            },
            {
                name: "Philippine Savings Bank",
                acronym: "PSBank",
                image: "images/psbank.png",
                "height": "60",
                "width": "125",
            },
            {
                name: "Asia United Bank",
                acronym: "AUB",
                image: "images/aub.png",
                "height": "85",
                "width": "145",
            },
            {
                name: "Philippine Bank of Communications",
                acronym: "PBCOM",
                image: "images/pbcom.png",
                "height": "80",
                "width": "135",
            },
            {
                name: "Bank of Commerce",
                acronym: "BOC",
                image: "images/boc.jpg",
                "height": "80",
                "width": "145",
            },
            {
                name: "Development Bank of the Philippines",
                acronym: "DBP",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "AllBank (A Thrift Bank), Inc.",
                acronym: "AllBank",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Bangko Mabuhay",
                acronym: "BM",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "BDO Network Bank",
                acronym: "BDO",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "BanKo",
                acronym: "BPI BanKo",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Cebuana Lhuillier Rural Bank, Inc.",
                acronym: "Cebuana Lhuillier",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "China Bank Savings, Inc.",
                acronym: "CBS",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Chinatrust Commercial Bank Corp.",
                acronym: "CTBC Bank",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Coins.ph (DCPay)",
                acronym: "Bitcoin",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Dungganon Bank Inc.",
                acronym: "DBI",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "EastWest Rural Bank, Inc.",
                acronym: "EastWest",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Equicom Savings Bank, Inc.",
                acronym: "Equicom",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "ING Bank N.V.",
                acronym: "ING",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Isla Bank (A Thrift Bank), Inc.",
                acronym: "Isla Bank",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Malayan Bank Savings and Mortgage Bank, Inc.",
                acronym: "Malayan Bank",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Maybank Philippines, Inc.",
                acronym: "Maybank",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "OmniPay, Inc.",
                acronym: "OmniPay",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Partner Rural Bank (Cotabato), Inc.",
                acronym: "Partner Rural Bank",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "PayMaya Philippines, Inc.",
                acronym: "PayMaya",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Philippines Business Bank, Inc. (A Savings Bank)",
                acronym: "PBB",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Philippines Trust Company",
                acronym: "Philtrust Bank",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Philippine Veterans Bank",
                acronym: "Veterans Bank",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Quezon Capital Rural Bank",
                acronym: "QCRB",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "RCBC Savings Bank, Inc.",
                acronym: "RCBC",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Robinsons Bank Corporation",
                acronym: "Robinsons Bank",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Sterling Bank of Asia, Inc. (A Savings Bank)",
                acronym: "Sterling",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Sun Savings Bank, Inc.",
                acronym: "Sun Savings",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "UCPB Savings Bank",
                acronym: "UCPB",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
            {
                name: "Wealth Development Bank",
                acronym: "WealthBank",
                image: "images/bank_transfer.png",
                "height": "100",
                "width": "100",
            },
        ]
}]);
